// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── All platforms now point to lockeriot-a9b55 ─────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3ZTyVgW1reaiWgMEqyIHBYCJ8-Qy23Y',
    authDomain: 'lockeriot-a9b55.firebaseapp.com',
    databaseURL:
        'https://lockeriot-a9b55-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'lockeriot-a9b55',
    storageBucket: 'lockeriot-a9b55.firebasestorage.app',
    messagingSenderId: '444042711269',
    appId: '1:444042711269:web:1aed0b1cdd719b882c840c',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3ZTyVgW1reaiWgMEqyIHBYCJ8-Qy23Y',
    authDomain: 'lockeriot-a9b55.firebaseapp.com',
    databaseURL:
        'https://lockeriot-a9b55-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'lockeriot-a9b55',
    storageBucket: 'lockeriot-a9b55.firebasestorage.app',
    messagingSenderId: '444042711269',
    appId: '1:444042711269:web:1aed0b1cdd719b882c840c',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf3ZTyVgW1reaiWgMEqyIHBYCJ8-Qy23Y',
    authDomain: 'lockeriot-a9b55.firebaseapp.com',
    databaseURL:
        'https://lockeriot-a9b55-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'lockeriot-a9b55',
    storageBucket: 'lockeriot-a9b55.firebasestorage.app',
    messagingSenderId: '444042711269',
    appId: '1:444042711269:web:1aed0b1cdd719b882c840c',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf3ZTyVgW1reaiWgMEqyIHBYCJ8-Qy23Y',
    authDomain: 'lockeriot-a9b55.firebaseapp.com',
    databaseURL:
        'https://lockeriot-a9b55-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'lockeriot-a9b55',
    storageBucket: 'lockeriot-a9b55.firebasestorage.app',
    messagingSenderId: '444042711269',
    appId: '1:444042711269:web:1aed0b1cdd719b882c840c',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf3ZTyVgW1reaiWgMEqyIHBYCJ8-Qy23Y',
    authDomain: 'lockeriot-a9b55.firebaseapp.com',
    databaseURL:
        'https://lockeriot-a9b55-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'lockeriot-a9b55',
    storageBucket: 'lockeriot-a9b55.firebasestorage.app',
    messagingSenderId: '444042711269',
    appId: '1:444042711269:web:1aed0b1cdd719b882c840c',
  );
}
